<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Brand;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // Lấy danh sách các hãng xe dựa trên Slug
        $honda   = Brand::where('slug', 'honda')->first();
        $yamaha  = Brand::where('slug', 'yamaha')->first();
        $sym     = Brand::where('slug', 'sym')->first();
        $piaggio = Brand::where('slug', 'piaggio')->first();
        $suzuki  = Brand::where('slug', 'suzuki')->first();

        // Lấy danh sách các danh mục xe (Loại xe)
        $xeSo   = Category::where('slug', 'xe-so')->first();
        $tayGa  = Category::where('slug', 'xe-tay-ga')->first();
        $conTay = Category::where('slug', 'xe-con-tay')->first();

        // Mảng chứa dữ liệu 35 xe máy (Mỗi hãng 7 xe)
        $products = [
            // ==================== HONDA (7 Xe) ====================
            [
                'name' => 'Honda Wave Alpha 110',
                'brand_id' => $honda?->id,
                'category_id' => $xeSo?->id,
                'price' => 18900000,
                'sale_price' => 18500000,
                'stock' => 15,
                'engine' => '110cc',
                'year' => '2024',
                'color' => 'Trắng, Xanh, Đỏ, Đen',
                'description' => 'Vua xe số tiết kiệm nhiên liệu, thiết kế nhỏ gọn, bền bỉ trên mọi chặng đường.',
                'is_featured' => true,
            ],
            [
                'name' => 'Honda Vision 110 Cao Cấp',
                'brand_id' => $honda?->id,
                'category_id' => $tayGa?->id,
                'price' => 33000000,
                'sale_price' => 32500000,
                'stock' => 20,
                'engine' => '110cc',
                'year' => '2024',
                'color' => 'Xanh xi măng, Đỏ đen',
                'description' => 'Xe tay ga quốc dân dành cho phái đẹp, kiểu dáng thời trang, trang bị Smartkey.',
                'is_featured' => true,
            ],
            [
                'name' => 'Honda Air Blade 125 Tiêu Chuẩn',
                'brand_id' => $honda?->id,
                'category_id' => $tayGa?->id,
                'price' => 42000000,
                'sale_price' => null,
                'stock' => 12,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Xanh Đen, Đỏ Đen',
                'description' => 'Thiết kế thể thao mạnh mẽ nam tính, trang bị động cơ eSP+ thế hệ mới.',
                'is_featured' => false,
            ],
            [
                'name' => 'Honda SH Mode 125',
                'brand_id' => $honda?->id,
                'category_id' => $tayGa?->id,
                'price' => 58000000,
                'sale_price' => 57000000,
                'stock' => 8,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Trắng Nâu, Đỏ Đen',
                'description' => 'Chuẩn mực phong cách châu Âu thời thượng, sang trọng và quý phái.',
                'is_featured' => false,
            ],
            [
                'name' => 'Honda Winner X Thể Thao',
                'brand_id' => $honda?->id,
                'category_id' => $conTay?->id,
                'price' => 46000000,
                'sale_price' => 41000000,
                'stock' => 25,
                'engine' => '150cc',
                'year' => '2024',
                'color' => 'Đỏ Đen Bạc, Đen Vàng',
                'description' => 'Xe côn tay thế hệ mới, phanh ABS an toàn, kiểu dáng siêu ngầu.',
                'is_featured' => true,
            ],
            [
                'name' => 'Honda Future 125 Fi',
                'brand_id' => $honda?->id,
                'category_id' => $xeSo?->id,
                'price' => 31500000,
                'sale_price' => 31000000,
                'stock' => 10,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Xanh Lịch Lãm, Đỏ Đô',
                'description' => 'Xe số cao cấp lịch lãm, tiết kiệm xăng tối đa, cốp xe rộng rãi.',
                'is_featured' => false,
            ],
            [
                'name' => 'Honda Lead 125 Cao Cấp',
                'brand_id' => $honda?->id,
                'category_id' => $tayGa?->id,
                'price' => 41500000,
                'sale_price' => null,
                'stock' => 18,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Vàng nhạt, Xanh cốm',
                'description' => 'Cốp siêu rộng 37 lít thách thức mọi vật dụng, xe ga lý tưởng cho gia đình.',
                'is_featured' => false,
            ],

            // ==================== YAMAHA (7 Xe) ====================
            [
                'name' => 'Yamaha Exciter 155 VVA',
                'brand_id' => $yamaha?->id,
                'category_id' => $conTay?->id,
                'price' => 48000000,
                'sale_price' => 47200000,
                'stock' => 30,
                'engine' => '155cc',
                'year' => '2024',
                'color' => 'Xanh GP, Đen Nhám',
                'description' => 'Tiểu YZF-R1 trong phân khúc côn tay, trang bị van biến thiên VVA siêu bốc.',
                'is_featured' => true,
            ],
            [
                'name' => 'Yamaha Sirius 110',
                'brand_id' => $yamaha?->id,
                'category_id' => $xeSo?->id,
                'price' => 19000000,
                'sale_price' => 18800000,
                'stock' => 40,
                'engine' => '110cc',
                'year' => '2024',
                'color' => 'Đỏ Đen, Xám Đen',
                'description' => 'Dòng xe số bền bỉ, máy khỏe, tăng tốc nhanh, thiết kế gọn gàng sắc sảo.',
                'is_featured' => false,
            ],
            [
                'name' => 'Yamaha Grande Blue Core Hybrid',
                'brand_id' => $yamaha?->id,
                'category_id' => $tayGa?->id,
                'price' => 46000000,
                'sale_price' => 45500000,
                'stock' => 14,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Trắng Ngọc Trai, Đỏ Nữ Tính',
                'description' => 'Nữ hoàng tiết kiệm xăng phân khúc xe ga, động cơ Hybrid cực êm ái.',
                'is_featured' => true,
            ],
            [
                'name' => 'Yamaha Janus 125 Tiêu Chuẩn',
                'brand_id' => $yamaha?->id,
                'category_id' => $tayGa?->id,
                'price' => 29000000,
                'sale_price' => null,
                'stock' => 22,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Đen Tuyền, Trắng Sữa',
                'description' => 'Thiết kế trẻ trung năng động dành cho sinh viên, trọng lượng siêu nhẹ.',
                'is_featured' => false,
            ],
            [
                'name' => 'Yamaha NVX 155 VVA Thế Hệ Mới',
                'brand_id' => $yamaha?->id,
                'category_id' => $tayGa?->id,
                'price' => 55000000,
                'sale_price' => 54500000,
                'stock' => 11,
                'engine' => '155cc',
                'year' => '2024',
                'color' => 'Xám Ánh Xanh, Đen Vàng',
                'description' => 'Siêu xe tay ga thể thao phân khối nhỏ, bánh lốp to bám đường, phanh ABS cực đỉnh.',
                'is_featured' => false,
            ],
            [
                'name' => 'Yamaha Jupiter Finn',
                'brand_id' => $yamaha?->id,
                'category_id' => $xeSo?->id,
                'price' => 28000000,
                'sale_price' => null,
                'stock' => 15,
                'engine' => '115cc',
                'year' => '2024',
                'color' => 'Xanh Xám, Bạc',
                'description' => 'Xe số gia đình trang bị phanh kết hợp UBS an toàn, cân bằng lực phanh xuất sắc.',
                'is_featured' => false,
            ],
            [
                'name' => 'Yamaha YZF-R15 V4',
                'brand_id' => $yamaha?->id,
                'category_id' => $conTay?->id,
                'price' => 78000000,
                'sale_price' => 76000000,
                'stock' => 5,
                'engine' => '155cc',
                'year' => '2024',
                'color' => 'Xanh Racing, Đen Bóng',
                'description' => 'Sportbike phân khối nhỏ đẳng cấp thể thao đường phố, trang bị Quickshifter.',
                'is_featured' => true,
            ],

            // ==================== SYM (7 Xe) ====================
            [
                'name' => 'SYM Attila 125 New',
                'brand_id' => $sym?->id,
                'category_id' => $tayGa?->id,
                'price' => 33500000,
                'sale_price' => 33000000,
                'stock' => 10,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Đỏ Cổ Điển, Trắng Tinh Khôi',
                'description' => 'Sự trở lại của huyền thoại Attila, dáng thời trang cổ điển phong cách Ý.',
                'is_featured' => false,
            ],
            [
                'name' => 'SYM Elegant 110',
                'brand_id' => $sym?->id,
                'category_id' => $xeSo?->id,
                'price' => 17000000,
                'sale_price' => null,
                'stock' => 35,
                'engine' => '110cc',
                'year' => '2024',
                'color' => 'Xanh Đen, Đỏ Đen',
                'description' => 'Lựa chọn xe số giá rẻ lý tưởng, máy chạy bền chịu lực tốt.',
                'is_featured' => false,
            ],
            [
                'name' => 'SYM Star SR 125 EFI',
                'brand_id' => $sym?->id,
                'category_id' => $xeSo?->id,
                'price' => 28500000,
                'sale_price' => 27500000,
                'stock' => 12,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Đỏ Đen, Đức Vua Đen',
                'description' => 'Xe số thể thao trang bị phun xăng điện tử và lốp không săm phong cách.',
                'is_featured' => false,
            ],
            [
                'name' => 'SYM Galaxy 115',
                'brand_id' => $sym?->id,
                'category_id' => $xeSo?->id,
                'price' => 18000000,
                'sale_price' => null,
                'stock' => 20,
                'engine' => '115cc',
                'year' => '2024',
                'color' => 'Đen Đỏ, Đen Xanh',
                'description' => 'Thiết kế góc cạnh cá tính mạnh mẽ cho các bạn nam sinh viên.',
                'is_featured' => false,
            ],
            [
                'name' => 'SYM Posh 50cc',
                'brand_id' => $sym?->id,
                'category_id' => $tayGa?->id,
                'price' => 24000000,
                'sale_price' => null,
                'stock' => 25,
                'engine' => '50cc',
                'year' => '2024',
                'color' => 'Hồng Kem, Xanh Ngọc',
                'description' => 'Xe tay ga 50cc không cần bằng lái, cực kỳ an toàn thời trang cho học sinh.',
                'is_featured' => true,
            ],
            [
                'name' => 'SYM Angela 50cc',
                'brand_id' => $sym?->id,
                'category_id' => $xeSo?->id,
                'price' => 16500000,
                'sale_price' => 16200000,
                'stock' => 30,
                'engine' => '50cc',
                'year' => '2024',
                'color' => 'Trắng Hồng, Xanh Trắng',
                'description' => 'Xe số 50cc nhẹ nhàng thanh lịch cho nữ sinh đến trường.',
                'is_featured' => false,
            ],
            [
                'name' => 'SYM Husky Classic 125',
                'brand_id' => $sym?->id,
                'category_id' => $conTay?->id,
                'price' => 34000000,
                'sale_price' => null,
                'stock' => 6,
                'engine' => '125cc',
                'year' => '2024',
                'color' => 'Đen Bóng, Xanh Rêu',
                'description' => 'Dòng côn tay Classic hoài cổ mang phong cách bụi bặm, lãng tử.',
                'is_featured' => true,
            ],

            // ==================== PIAGGIO (7 Xe) ====================
            [
                'name' => 'Vespa Primavera 125',
                'brand_id' => $piaggio?->id,
                'category_id' => $tayGa?->id,
                'price' => 79000000,
                'sale_price' => 78000000,
                'stock' => 10,
                'engine' => '125cc iGet',
                'year' => '2024',
                'color' => 'Trắng Băng, Vàng Chanh',
                'description' => 'Biểu tượng thời trang lãng mạn nước Ý, động cơ iGet giảm ồn tối đa.',
                'is_featured' => true,
            ],
            [
                'name' => 'Vespa Sprint Justin Bieber Edition',
                'brand_id' => $piaggio?->id,
                'category_id' => $tayGa?->id,
                'price' => 115000000,
                'sale_price' => null,
                'stock' => 2,
                'engine' => '150cc iGet',
                'year' => '2024',
                'color' => 'Trắng Full Bieber',
                'description' => 'Phiên bản giới hạn kết hợp cùng ngôi sao Justin Bieber, cực hiếm.',
                'is_featured' => true,
            ],
            [
                'name' => 'Vespa GTS Super 150',
                'brand_id' => $piaggio?->id,
                'category_id' => $tayGa?->id,
                'price' => 115000000,
                'sale_price' => 112000000,
                'stock' => 4,
                'engine' => '150cc',
                'year' => '2024',
                'color' => 'Đen Thạch Anh, Xanh Thẫm',
                'description' => 'Khung sườn thép nguyên khối cỡ lớn thể thao, mạnh mẽ vững chãi.',
                'is_featured' => false,
            ],
            [
                'name' => 'Piaggio Liberty 125 One',
                'brand_id' => $piaggio?->id,
                'category_id' => $tayGa?->id,
                'price' => 49000000,
                'sale_price' => null,
                'stock' => 16,
                'engine' => '125cc iGet',
                'year' => '2024',
                'color' => 'Đen Bóng, Trắng',
                'description' => 'Xe tay ga bánh lớn phong cách tự do đô thị, tư thế ngồi siêu tôn dáng.',
                'is_featured' => false,
            ],
            [
                'name' => 'Piaggio Medley S 150 ABS',
                'brand_id' => $piaggio?->id,
                'category_id' => $tayGa?->id,
                'price' => 95000000,
                'sale_price' => 94000000,
                'stock' => 5,
                'engine' => '150cc iGet',
                'year' => '2024',
                'color' => 'Đỏ Nhám, Xám Xe Tăng',
                'description' => 'Xe ga công nghệ cao, phanh ABS đôi, kết nối điện thoại thông minh qua MIA.',
                'is_featured' => false,
            ],
            [
                'name' => 'Vespa LX 125 Classic',
                'brand_id' => $piaggio?->id,
                'category_id' => $tayGa?->id,
                'price' => 68000000,
                'sale_price' => null,
                'stock' => 7,
                'engine' => '125cc iGet',
                'year' => '2024',
                'color' => 'Đỏ Cherry, Kem',
                'description' => 'Vẻ đẹp cổ điển trường tồn qua thời gian, đường nét bo tròn quý phái.',
                'is_featured' => false,
            ],
            [
                'name' => 'Vespa Sei Giorni II 300cc',
                'brand_id' => $piaggio?->id,
                'category_id' => $tayGa?->id,
                'price' => 139000000,
                'sale_price' => 137000000,
                'stock' => 2,
                'engine' => '300cc HPE',
                'year' => '2024',
                'color' => 'Xanh Nhám Đua',
                'description' => 'Chiến mã tay ga phân khối lớn mang phong cách xe đua cổ điển huyền thoại.',
                'is_featured' => true,
            ],

            // ==================== SUZUKI (7 Xe) ====================
            [
                'name' => 'Suzuki Raider R150 Fi',
                'brand_id' => $suzuki?->id,
                'category_id' => $conTay?->id,
                'price' => 51000000,
                'sale_price' => 49900000,
                'stock' => 20,
                'engine' => '150cc DOHC',
                'year' => '2024',
                'color' => 'Xanh Đen Suzuki, Đỏ Đen',
                'description' => 'Kiểu dáng độc độc Hyper Underbone, vua tăng tốc đường ngắn, động cơ DOHC.',
                'is_featured' => true,
            ],
            [
                'name' => 'Suzuki Satria F150 Nhập Khẩu',
                'brand_id' => $suzuki?->id,
                'category_id' => $conTay?->id,
                'price' => 53500000,
                'sale_price' => null,
                'stock' => 15,
                'engine' => '150cc DOHC',
                'year' => '2024',
                'color' => 'Trắng Đỏ Đen, Xanh Titan',
                'description' => 'Bản nhập khẩu chính ngạch Indonesia nguyên chiếc, sức mạnh nguyên bản hoang dã.',
                'is_featured' => true,
            ],
            [
                'name' => 'Suzuki Burgman Street 125',
                'brand_id' => $suzuki?->id,
                'category_id' => $tayGa?->id,
                'price' => 48600000,
                'sale_price' => 48000000,
                'stock' => 12,
                'engine' => '125cc SEP',
                'year' => '2024',
                'color' => 'Vàng Đồng, Xám mờ',
                'description' => 'Xe ga Maxi-scooter sang trọng cho quý ông đường trường, sàn để chân rộng.',
                'is_featured' => false,
            ],
            [
                'name' => 'Suzuki GSX-R150 Thể Thao',
                'brand_id' => $suzuki?->id,
                'category_id' => $conTay?->id,
                'price' => 72000000,
                'sale_price' => 69000000,
                'stock' => 5,
                'engine' => '150cc DOHC',
                'year' => '2024',
                'color' => 'Xanh Trắng Racing',
                'description' => 'Trọng lượng nhẹ nhất phân khúc Sportbike 150cc mang lại tỷ lệ công suất vượt trội.',
                'is_featured' => false,
            ],
            [
                'name' => 'Suzuki GSX-S150 Naked',
                'brand_id' => $suzuki?->id,
                'category_id' => $conTay?->id,
                'price' => 64000000,
                'sale_price' => null,
                'stock' => 6,
                'engine' => '150cc',
                'year' => '2024',
                'color' => 'Đen Nhám, Xanh Đen',
                'description' => 'Dòng Nakedbike gọn gàng đi phố linh hoạt, góc lái rộng thoải mái.',
                'is_featured' => false,
            ],
            [
                'name' => 'Suzuki Viva 115 Fi',
                'brand_id' => $suzuki?->id,
                'category_id' => $xeSo?->id,
                'price' => 22000000,
                'sale_price' => null,
                'stock' => 14,
                'engine' => '115cc Fi',
                'year' => '2024',
                'color' => 'Trắng Xanh, Đen',
                'description' => 'Xe số bền bỉ, công nghệ tiết kiệm xăng LEaP vượt bậc đã được khẳng định.',
                'is_featured' => false,
            ],
            [
                'name' => 'Suzuki GZ150-A Cruiser',
                'brand_id' => $suzuki?->id,
                'category_id' => $conTay?->id,
                'price' => 40500000,
                'sale_price' => null,
                'stock' => 8,
                'engine' => '150cc',
                'year' => '2024',
                'color' => 'Đen Huyền Bí',
                'description' => 'Hành trình bất tận cùng phong cách thuần Cruiser đường trường lịch lãm, đi kèm 2 thùng hông.',
                'is_featured' => true,
            ],
        ];

        // ── Thêm dữ liệu vào database và cấu hình slug/ảnh đại diện ──
        foreach ($products as $p) {
            $p['slug'] = Str::slug($p['name']) . '-' . time();
            $p['is_active'] = true;
            $p['image'] = null; // Sẽ hiển thị ảnh Placeholder tự động ngoài view nếu rỗng
            
            Product::create($p);
        }
    }
}